name: pushnotification_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^1.24.0
  firebase_auth: ^3.8.0
  firebase_messaging: ^13.0.4
  overlay_support: ^2.0.1
  cloud_firestore: ^3.5.0
  flutter: 
    sdk: flutter
  flutter_local_notifications: ^11.0.1
  http: ^0.13.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

